### ISSUE TITLE
Customer class (properties, rent/cancel item, return item, and transaction history)

### ISSUE THREAD

**Issue by SeanBlackford** [SeanBlackford37/Music-Store-Rehearsal-Space#10]
How to Demo:
Assigns customer to a store
Rent a "guitar" from the store
check if the "guitar" is in inventory
return price of the rental
ask customer if they want to rent
if customer confirms can cancel anytime
update inventory list
update rented list
update item renter name
update transaction history list
if customer returns item
update item renter name
update rented list
update inventory list

**Comment by embieck** [comment]
Actual Time: 5

The additional methods and tests contributed to the extra time
