### ISSUE TITLE
Customer Can both rent a room and equipment

### ISSUE THREAD

**Issue by mziegler611** [SeanBlackford37/Music-Store-Rehearsal-Space#42]
How To Demo:
Have a customer rent a room
Then have a customer rent equipment
Make sure the room is no longer open
Make sure the equipment is now rented and out of inventory
Then be able to cancel the room 
Then cancel the equipment

**Comment by SeanBlackford** [comment]
Hours worked: 30mins
Demo of renting a room and renting equipment, having tests done on them. Returning equipment and canceling room rental. Each rent or return has checks to make sure they are out of the list and put in the proper one. (Customer rent a room and equipment can be found in CustomerTest)
