### ISSUE TITLE
Changing transactions to allow renting multiple items at once

### ISSUE THREAD

**Issue by embieck** [SeanBlackford37/Music-Store-Rehearsal-Space#56]
# How to demo:
## customer rents multiple items in a single transaction
- order amount should reflect aggregate cost
- all items should be added to customer rented list
- all items should be moved to store rented list
- all items should be recorded in the transaction
- all items must be checked that they're available for rent
- all items renter name should be updated

## if list of items contains unavailable items
- add the available ones
- throw an error/print a message for the unavailable ones
- check for the information listed above for the available items

**Comment by SeanBlackford** [comment]
Hours worked: 1h 30mins
Allow the customer to rent multiple items with the items go into a single transaction, instead of having multiple transactions
