### ISSUE TITLE
Enable customer to cancel, return multiple items at once and combine item with renting room into a single transaction 

### ISSUE THREAD

**Issue by embieck** [SeanBlackford37/Music-Store-Rehearsal-Space#57]
# How to Demo:

## rent multiple items
- check all the information for the items have been updated
- check that transaction has been updated
- check that store info is updated
- check all customer records are updated
- exception thrown for unavailable items

## rent item and a room
- check all the information for the items have been updated
- check all the information for the rooms has been updated
- check that transaction has been updated
- check that store info is updated
- check all customer records are updated
- check room is added to the transaction as well 
- exception thrown for unavailable items

## cancel multiple items
- check all the information for the items have been updated
- check that transaction has been updated just for items being canceled and order amount
- check that store info is updated
- check all customer records are updated
- exception thrown for items listed that haven't been rented

## return multiple items
- nothing is done to transaction 
- info for items is updated
- store info is also updated
- exception thrown for items listed that haven't been rented

*These changes can also be applied to when items and a room are being rented
*Additional testing will be required to ensure the room info is left alone while all of this is done

**Comment by SeanBlackford** [comment]
Issues: Transaction history should it only update when returning items or renting? Not to delete them?

**Comment by embieck** [comment]
How it's written, transactions are removed only when an item or a room is canceled. I figured that when canceling the item or the room being rented, the multiple transaction could just be changed to a single room/item transaction. And the single transaction could be returned to the position in the transaction history where the original transaction was located.

**Comment by SeanBlackford** [comment]
Ah I get now, I have to change the UI as well. I thought I had to use cancel items to return items. Thanks

**Comment by SeanBlackford** [comment]
Hours worked: 3h 40mins
Work done: added  the ability to rent/cancel/return multiple items at once. Also with having multiple items this is updated in their respective transactions as well. Everything was tested to make sure no errors would happen when having multiple items.
